### ISSUE TITLE
init_mr_mime() takes exactly 1 argument

### ISSUE THREAD

**Issue by Ben-13** [sLoPPydrive/PGNumbra#10]
Not sure if i'm missing something or config.json changed?  Since the last pull I get the title error no matter what I do.  "init_mr_mime() takes exactly 1 argument" ?

**Comment by sLoPPydrive** [comment]
You should do a reinstall of MrMime (besides a `git pull`):
```
pip uninstall mrmime
pip install -r requirements.txt --upgrade
```
Let me know if this works. :)

**Comment by Ben-13** [comment]
That did let me get past it, wasn't even thinking... (I was running without --upgrade, might want to add that as a "how to update" :) ) 

Now though I'm getting this:

2017-06-30 00:31:50,720 [        Thread-1][   shadowcheck][   ERROR] Error checking account 
Traceback (most recent call last):
  File "shadowcheck.py", line 82, in check_account
    torch.scan_once()
  File "C:\Pogo-map\PGNumbra\pgnumbra\SingleLocationScanner.py", line 36, in scan_once
    if self.check_login():
  File "C:\Python27\lib\site-packages\mrmime\pogoaccount.py", line 147, in check_login
    self._proxy_url = self._proxy_provider.next()
  File "C:\Python27\lib\site-packages\mrmime\cyclicresourceprovider.py", line 32, in next
    raise Exception("CyclicResourceProvider without any resource!")
Exception: CyclicResourceProvider without any resource!

Let me know if you'd rather this as a separate issue.

**Comment by sLoPPydrive** [comment]
I fixed this bug some days ago with a new commit to MrMime. Can you please check again? :) See above on how to update...

**Comment by Ben-13** [comment]
That fixed it, thank you!
