### ISSUE TITLE
SingleLocationScanner.py error

### ISSUE THREAD

**Issue by tokar86a** [sLoPPydrive/PGNumbra#15]
sername or password is incorrect. You have 2 attempts left before you will be locked out of your account for 15 minutes.',) - Trying again in 6 seconds.
2017-10-27 21:59:53,302 [       Thread-11][   shadowcheck][   ERROR] Error checking account t06286s20: AuthException(u'Your username or password is incorrect. You have 2 attempts left before you will be locked out of your account for 15 minutes.',)
Traceback (most recent call last):
  File "shadowcheck.py", line 48, in check_account
    response = acc.scan_once()
  File "C:\Users\Pikachu\Documents\PGNumbra\pgnumbra\SingleLocationScanner.py", line 35, in scan_once
    if self.check_login():
  File "C:\Python27\lib\site-packages\mrmime\pogoaccount.py", line 256, in check_login
    'https': self._proxy_url
  File "C:\Python27\lib\site-packages\pgoapi\pgoapi.py", line 132, in set_authentication
    if not self._auth_provider.user_login(username, password):
  File "C:\Python27\lib\site-packages\pgoapi\auth_ptc.py", line 153, in user_login
    raise AuthException(j['errors'][0])
AuthException: Your username or password is incorrect. You have 2 attempts left before you will be locked out of your account for 15 minutes.

**Comment by jdggraaf** [comment]
So.. ya made a mistake in the accounts.csv or you didn't verify your account in time.

**Comment by sLoPPydrive** [comment]
Double-check the login on www.pokemon.com
