### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by jhrt80** [sLoPPydrive/PGNumbra#5]
"/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 3 column 21 (char 47)

same issue on Mac and PC so I assume I did something wrong.  Can you help?

**Comment by sLoPPydrive** [comment]
This is a syntax error in your 'config.json' file. Please check again and/or use an online JSON validator to find the error. :)

**Comment by jhrt80** [comment]
Thanks, i figured that out now I am having this issue.

$ python shadowcheck.py
Traceback (most recent call last):
  File "shadowcheck.py", line 7, in <module>
    from pgnumbra.Torch import Torch
  File "C:\Users\Juan\PGNumbra-master\pgnumbra\Torch.py", line 7, in <module>
    from pgnumbra.POGOAccount import POGOAccount
  File "C:\Users\Juan\PGNumbra-master\pgnumbra\POGOAccount.py", line 12, in <module>
    from pgnumbra.config import cfg_get
  File "C:\Users\Juan\PGNumbra-master\pgnumbra\config.py", line 29, in <module>
    user_cfg = json.loads(f.read())
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

This is the config file 

{
  "latitude": 40.771245,
  "longitude": -111.887435,
  "hash_key": "took this out",
  "accounts_file": C:\Users\Juan\PGNumbra-master\accounts.json,
  "proxies_file": "",
  "scan_retries": 3,
  "include_nearby": false,
  "pokemon_name_format": full,
  "shadowcheck_threads": 10
}
