### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by jhrt80** [sLoPPydrive/PGNumbra#6]
can you help with this one?

$ python shadowcheck.py
Traceback (most recent call last):
File "shadowcheck.py", line 7, in 
from pgnumbra.Torch import Torch
File "C:\Users\Juan\PGNumbra-master\pgnumbra\Torch.py", line 7, in 
from pgnumbra.POGOAccount import POGOAccount
File "C:\Users\Juan\PGNumbra-master\pgnumbra\POGOAccount.py", line 12, in 
from pgnumbra.config import cfg_get
File "C:\Users\Juan\PGNumbra-master\pgnumbra\config.py", line 29, in 
user_cfg = json.loads(f.read())
File "C:\Python27\lib\json_init_.py", line 339, in loads
return _default_decoder.decode(s)
File "C:\Python27\lib\json\decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

This is the config file

{
"latitude": 40.771245,
"longitude": -111.887435,
"hash_key": "took this out",
"accounts_file": C:\Users\Juan\PGNumbra-master\accounts.json,
"proxies_file": "",
"scan_retries": 3,
"include_nearby": false,
"pokemon_name_format": full,
"shadowcheck_threads": 10
}

**Comment by walaoaaa1234** [comment]
@jhrt80 try this?
```
{
"latitude": 40.771245,
"longitude": -111.887435,
"hash_key": "took this out",
"accounts_file": "C:/Users/Juan/PGNumbra-master/accounts.json", <<<<<<<<<<
"proxies_file": "",
"scan_retries": 3,
"include_nearby": false,
"pokemon_name_format": "full", <<<<<<<<<<
"shadowcheck_threads": 10
}
```

**Comment by jhrt80** [comment]
That worked.  Thanks for your help.
